### ISSUE TITLE
Migrate from Maven to Gradle

### ISSUE THREAD

**Issue by steve-todorov** [uploadcare/uploadcare-java#62]
# Task Description

Migrate from Maven to Gradle in order to provide an unified developer experience and take advantage of cached tasks and other .

# Tasks

The following tasks will need to be carried out:

* [x] Migrate the current Maven project to Gradle.
* [x] Update the workflow to reflect the new changes.
* [x] Update the `README.md` 

# Task Relationships

This task:
* Is a sub-task of: #
* Depends on: #
* Is a follow-up of: #
* Relates to: #

# Help

* Points of contact:
  * @carlspring
  * @steve-todorov
  * @rsedykh
